resources:
- repo: self
phases:
#Multi-configuration and multi-agent job options are not exported to YAML. Configure these options using documentation guidance: https://docs.microsoft.com/vsts/pipelines/process/phases

- phase: Phase_1
  displayName: Build and Test

  condition: succeeded()
  queue:
    name: Hosted Linux Preview
  variables:
    python.version: '2.7, 3.5, 3.6, >= 3.7.0a'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'


  - script: 'python -m pip install --upgrade pip && pip install -r requirements.txt' 
    displayName: 'Install dependencies'

  - script: 'pip install flake8 && flake8' 
    displayName: Flake8
    enabled: false
    continueOnError: true

  - script: 'pip install pytest && pytest tests --doctest-modules --junitxml=junit/test-results.xml' 
    displayName: pytest

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/test-results.xml'
    inputs:
      testResultsFiles: '**/test-results.xml'

      testRunTitle: 'Python $(python.version)'



- phase: Phase_2
  displayName: Publish

  dependsOn: Phase_1
  condition: succeeded()
  queue:
    name: Hosted Linux Preview
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python >= 3.6'
    inputs:
      versionSpec: '>= 3.6'


  - script: 'python setup.py sdist' 
    displayName: 'Build sdist'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dist'
    inputs:
      PathtoPublish: dist

      ArtifactName: dist


  - task: PyPIPublisher@0
    displayName: 'Package and publish to PyPI'
    inputs:
      packageDirectory: '$(Build.SourcesDirectory)'

    enabled: false


